name: keep-supabase-alive

on:
  schedule:
    - cron: "0 */12 * * *"   # 12 giờ/lần (UTC) → VN chạy 07:00 & 19:00
  workflow_dispatch:         # Cho phép bấm chạy thủ công

permissions:
  contents: read

concurrency:
  group: keep-supabase-alive
  cancel-in-progress: false

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Ping Supabase Auth settings
        run: |
          set -e
          CODE=$(curl -sS -o /dev/null -w "%{http_code}" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            --max-time 20 --fail \
            "${{ secrets.SUPABASE_URL }}/auth/v1/settings")
          echo "HTTP $CODE"
